### ISSUE TITLE
Eventful Date Range Argument is incorrect

### ISSUE THREAD

**Issue by nickspeal** [nickspeal/musicThisWeek#8]
Eventful supports date ranges specified as follows:

> Limit this list of results to a date range, specified by label or exact range. Currently supported labels include: "All", "Future", "Past", "Today", "Last Week", "This Week", "Next week", and months by name, e.g. "October". Exact ranges can be specified the form 'YYYYMMDD00-YYYYMMDD00', for example '2012042500-2012042700'; the last two digits of each date in this format are ignored.
> 
> http://api.eventful.com/docs/events/search

Right now we let the user specify an arbitrary string and if incorrect, the date parameter is silently ignored by Eventful and something like all future events is returned. 

I'm not sure exactly what we want the UX to be, but let's discuss that here.

Some options:
1. Provide two fields: one for start date and another for end date. Default them to be today and today+7. 
2. "Next {} {}" specifying a number of days or weeks or months like "Next 7 days" or Next 2 months" and then parsing that.

**Comment by esmason** [comment]
I like option 1. Maybe we could add the potential option of clicking radios that say "Tonight" or "This Weekend" instead of specifying the date as well.  Html probably has some simple (bland looking) version of date select, and down the line we can probably plug a nice looking template.  https://github.com/asaglimbeni/django-datetime-widget

Importantly I think we can (and should aim to) eliminate typing things into the UI. This will make it easier to handle submissions and also make the website less vulnerable  (esp once we have db).

**Comment by nickspeal** [comment]
Sounds good. Can you please implement it? HTML is in the templates
directory.

At some point I'd like to do a proper design pass, so I wouldn't bother
doing anything to make it look prettier yet.

**Comment by esmason** [comment]
yep I will. ok sounds good
